### ISSUE TITLE
[IMPROVEMENT] - Faucet pull countdown/timer in negative faucet response

### ISSUE THREAD

**Issue by jackalyst** [theqrl-community/tipbot#13]
Right now when someone issues a the `+faucet` command when they've already withdrawn within a 24 hour period, it responds back with the information that they've already pulled from the faucet recently. 

As it can be difficult to discern when the faucet will be ready to pull from again, adding a timer to the faucet response to indicate the next time someone can initiate the faucet command would help.

Suggested by Discord user MrTr3

**Comment by fr1t2** [comment]
closed with #14
