### ISSUE TITLE
[IMPROVEMENT] - Clean tipbot tip messages after a set duration

### ISSUE THREAD

**Issue by jackalyst** [theqrl-community/tipbot#20]
### What would you like improved?

After a period of time, (15min?), clear the inline tipbot confirmation messages when sending a tip.

### Improvement 

It seems that the tipbot messages are there to indicate a successful transfer, but after they are read, they served its purpose. Beyond that, for record keeping, a message is also sent in the DM.

Should a public way to indicate a tip is sent be still desired, a cleaner way could be to add an emoji to the person tipping when it's been complete.

**Comment by fr1t2** [comment]
Closed with #21 removing messages after initial time frame for most bot messages.
