### ISSUE TITLE
[BUG] - Different tip amounts results in an error and no transaction sent

### ISSUE THREAD

**Issue by jackalyst** [theqrl-community/tipbot#24]
### Describe the bug

Certain amounts when tipping results in the error: "Invalid Amount Given", when it is a completely valid amount (a positive Float of between 10^-9 and 105000000 QRL)

### To Reproduce

1. Go to the QRL Discord
2. Enter the values 64.01, 32.307, 32.258, or 4.2288 as a tipbot amount
3. See error

### Expected behavior

No error with the transaction going through

### Screenshots

![Screenshot from 2021-12-22 14-29-10](https://user-images.githubusercontent.com/232510/147157364-f7b2647c-f3a8-4212-bb4d-18c367454141.png)

### Environment 

- Discord linux application

**Comment by fr1t2** [comment]
This is fixed with PR #25, Thanks @jackalyst
